main = ".open-next/worker.js"
name = "onenav"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
[[d1_databases]]
binding = "onenav"
database_name = "onenav"
database_id = "a75b2979-1e52-40d3-a3a6-ca0abec3482d"